---
arch: amd64
os: linux
dist: focal

language: go

go:
  - "${GO_RELEASE}"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version # prints the Hugo version
  - hugo -d ./build # build the website

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    - PRODUCTION=true
    - GO_RELEASE=1.14.x
    - HUGO_RELEASE=0.78.2