name: Deploy project
on:
  workflow_run:
    workflows: Build project
    branches: main
    types: completed
jobs:
  deploy-project:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./out/
          server-dir: ./www/